title: MM Remote Theme Test
email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: /mm-remote-theme-test
url: https://mmistakes.github.io
twitter_username: mmistakes
github_username: mmistakes
minimal_mistakes_skin: dark

remote_theme: "mmistakes/minimal-mistakes@4.15.2"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache